name: Generate release-artifacts

on:
  push:
    tags:
      - '*'

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
          platforms: 'linux/amd64, linux/arm'
          package: 'homeSerBot'
          name: 'HomeSerBot'
          compress: 'true'
          dest: 'builds'