name: Build Release

on:
  release:
    types:
      - created

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate build files
        uses: netphantom/go-cross-build@master
        with:
          platforms: 'linux/amd64, linux/arm'
          package: ''
          name: 'HomeSerBot'
          compress: 'true'
          dest: 'builds'
          addfolder: 'ui'

      - name: Upload build-artifacts
        uses: skx/github-action-publish-binaries@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            args: "./builds/*.tar.gz"
