name: Build Release

on:
  release:
    types:
      - created

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Release Docker image on GitHub Packages
        uses: docker/build-push-action@v2
        with:
          file: docker/dockerfile
          push: true
          tags: latest

      - name: Generate build files
        uses: netphantom/go-cross-build@master
        with:
          platforms: 'linux/amd64, linux/arm'
          package: ''
          name: 'HomeSerBot'
          compress: 'true'
          dest: 'builds'
          addfolder: 'ui'

      - name: Upload build-artifacts
        uses: skx/github-action-publish-binaries@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            args: "./builds/*.tar.gz"
